template(name="SshAttemptMessage" type="string" string="%msg:::drop-last-lf%\n")

if $programname == 'sshd' and ($msg contains 'Failed password' or $msg contains 'Invalid user' or $msg contains 'Disconnected from authenticating user') then {
  action(
    type="omfwd"
    target="127.0.0.1"
    port="7070"
    protocol="tcp"
    template="SshAttemptMessage"
    action.resumeRetryCount="-1"
    queue.type="linkedList"
    queue.filename="ssh-geohash"
  )
}
